"""reusable diet menus (food, meal_template, menu) replacing direct meal/meal_item

Revision ID: 48138cef2ae6
Revises: 5db6ee93035f
Create Date: 2026-08-01 22:58:48.303168

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "48138cef2ae6"
down_revision: Union[str, Sequence[str], None] = "5db6ee93035f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "foods",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("trainer_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("unit_label", sa.String(length=50), nullable=False),
        sa.Column("calories", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("protein_g", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("carbs_g", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("fat_g", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["trainer_id"],
            ["trainers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "meal_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("trainer_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["trainer_id"],
            ["trainers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "menus",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("trainer_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["trainer_id"],
            ["trainers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "meal_template_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("meal_template_id", sa.UUID(), nullable=False),
        sa.Column("food_id", sa.UUID(), nullable=True),
        sa.Column("food_name", sa.String(length=255), nullable=False),
        sa.Column("quantity_label", sa.String(length=50), nullable=True),
        sa.Column(
            "quantity_multiplier", sa.Numeric(precision=6, scale=2), nullable=True
        ),
        sa.Column("calories", sa.Numeric(precision=6, scale=1), nullable=True),
        sa.Column("protein_g", sa.Numeric(precision=6, scale=1), nullable=True),
        sa.Column("carbs_g", sa.Numeric(precision=6, scale=1), nullable=True),
        sa.Column("fat_g", sa.Numeric(precision=6, scale=1), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["food_id"], ["foods.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["meal_template_id"],
            ["meal_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "menu_meals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("menu_id", sa.UUID(), nullable=False),
        sa.Column("meal_template_id", sa.UUID(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("time_of_day", sa.Time(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["meal_template_id"],
            ["meal_templates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["menu_id"],
            ["menus.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("meal_items")
    op.drop_table("meals")
    op.add_column("diet_days", sa.Column("menu_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "diet_days", "menus", ["menu_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "diet_days", type_="foreignkey")
    op.drop_column("diet_days", "menu_id")
    op.create_table(
        "meals",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("diet_day_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("order_index", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("time_of_day", postgresql.TIME(), autoincrement=False, nullable=True),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["diet_day_id"], ["diet_days.id"], name=op.f("meals_diet_day_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("meals_pkey")),
    )
    op.create_table(
        "meal_items",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("meal_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "food_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "quantity", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "calories",
            sa.NUMERIC(precision=6, scale=1),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "protein_g",
            sa.NUMERIC(precision=6, scale=1),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "carbs_g",
            sa.NUMERIC(precision=6, scale=1),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "fat_g",
            sa.NUMERIC(precision=6, scale=1),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("order_index", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["meal_id"], ["meals.id"], name=op.f("meal_items_meal_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("meal_items_pkey")),
    )
    op.drop_table("menu_meals")
    op.drop_table("meal_template_items")
    op.drop_table("menus")
    op.drop_table("meal_templates")
    op.drop_table("foods")
    # ### end Alembic commands ###
